### ISSUE TITLE
Add first moment inside interval

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/SingularIntegrals.jl#7]
We need the case `-1 ≤ z ≤ 1` added here:

https://github.com/JuliaApproximation/SingularIntegrals.jl/blob/941e9d12eb48045925d7da1c078d47236b059f48/src/power.jl#L21

**Comment by TSGut** [comment]
Ah, this is what I meant here https://github.com/JuliaApproximation/SingularIntegrals.jl/commit/a868f796e3284988ed3adec8c21511ab3dcc1f05#commitcomment-108450720

but I see now that the moment of degree 1 isn't there yet. I will add it
