### ISSUE TITLE
How close is this to being tagged and registered?

### ISSUE THREAD

**Issue by TSGut** [JuliaApproximation/SingularIntegrals.jl#9]
SemiclassicalOrthogonalPolynomials.jl depends on Associated (and possibly Hilbert though I am not sure that import is actually used anywhere) which has moved from ClassicalOPs.jl to here. 

As a result we are in a bit of a dependency mess because I want to use the latest version of ClassicalOPs.jl which has the QR/Cholesky jacobi matrices. (I can work around this locally but tests won't pass until this is resolved)

So - how close is this to being tagged and registered?

**Comment by dlfivefifty** [comment]
It takes 3 days.

It's not really a "mess": just `] add https://github.com/JuliaApproximation/SingularIntegrals.jl`

**Comment by TSGut** [comment]
There is more than that conflict with the latest main branch of ClassicalOPs, it's just the primary one (some of the others are due ClassicalOPs requiring new versions of e.g. ArrayLayouts and other packages after the v1 update). But it can all be circumvented locally by overwriting the dependency requirements, yes.

**Comment by dlfivefifty** [comment]
If those updates are an issue it just means other packages need to be tagged.
